FROM python:3.12.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . /app
COPY .streamlit /root/.streamlit

EXPOSE 8501

CMD ["streamlit", "run", "movie_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
