services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    command: ["streamlit", "run", "movie_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
